trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      pip install pylint
      pip install -r requirements.txt
      pylint py/covidlambda.py --reports=yes --output-format=msvs > report.txt
      ls -al
      ls -al py
  displayName: 'pylint'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'report.txt'
    publishLocation: 'pipeline'