trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      pip install pylint
      pip install -r requirements.txt
      mkdir tests
      ls -al
      pylint lambdafunction/covidlambda.py --exit-zero --reports=yes --output-format=msvs > tests/report.txt
  displayName: 'pylint'

- task: Python Unit Test@0
  inputs:
    pythonroot: 'lambdafunction'
    reqfile: 'requirements.txt'
    coveragedir: 'coverage'
    testfilepattern: 'test_.py'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud-covidlambda'
    organization: 'covidlambda'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'covidlambda'
    cliProjectName: 'COVIDlambda'
    cliSources: 'lambdafunction'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      pip install cfn-lint
      cfn-lint -I -f parseable cloudformation/covidlambda.yml > tests/cf.txt
  displayName: 'cfnlint'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'tests/'
    artifact: 'reports'
    publishLocation: 'pipeline'
  displayName: 'Publish reports'

- task: Bash@3
  inputs:
    filePath: 'virtualenv/scripts/virtualenv.sh'
  displayName: 'Create Virtualenv'

- task: Bash@3
  inputs:
    filePath: 'virtualenv/scripts/pack.sh'
  displayName: 'Create artifact'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'artifacts'
    ArtifactName: 'covidlambda'
    publishLocation: 'Container'